apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ktck
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rsoaresd_org/rhtap-demo-ibwj-tenant/rhtap-demo-app/hacbs-test-project-ktck@sha256:5bcd32f0b2be9561ba9669262d3ad206762f60b3c7e8e7146a4f29ef6469e094
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
